spring:
  application:
    name: api-gateway
  profiles:
    active: ${APP_PROFILE}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"

eureka:
  instance:
    instance-id: ${spring.application.name}:${HOSTNAME}
