openapi: 3.0.3
info:
  title: Vendo API
  version: 1.0.0
  description: Vendo Marketplace API

servers:
  - url: http://194.163.130.14:8030
    description: Vendo server

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      $ref: "./components/security.yaml"

paths:

  # ─── AUTH ────

  /auth/sign-up:
    $ref: "./paths/auth.yaml#/signUp"

  /auth/sign-in:
    $ref: "./paths/auth.yaml#/signIn"

  /auth/refresh:
    $ref: "./paths/auth.yaml#/refresh"

  /auth/google:
    $ref: "./paths/auth.yaml#/google"

  /auth/complete:
    $ref: "./paths/auth.yaml#/complete"

  /auth/me:
    $ref: "./paths/auth.yaml#/me"

  /password/forgot:
    $ref: "./paths/auth.yaml#/password"

  /password/reset:
    $ref: "./paths/auth.yaml#/reset"

  /password/resend:
    $ref: "./paths/auth.yaml#/resend"

  /verification/send-otp:
    $ref: "./paths/auth.yaml#/send-otp"

  /verification/validate:
    $ref: "./paths/auth.yaml#/validate"

  /verification/resend-otp:
    $ref: "./paths/auth.yaml#/resent-otp"

  # ─── SEARCH ───

  /search:
    $ref: "./paths/search.yaml#/search"

  # ─── PRODUCTS ───

  /categories:
    $ref: "./paths/product.yaml#/categories"

  /categories/tree:
    $ref: "./paths/product.yaml#/tree"

  /categories/{id}:
    $ref: "./paths/product.yaml#/category"

  /products:
    $ref: "./paths/product.yaml#/products"

  /products/{id}:
    $ref: "./paths/product.yaml#/product"

  /attributes:
    $ref: "./paths/product.yaml#/attributes"

  # ─── STORAGE ───

  /storage/presigned:
    $ref: "./paths/storage.yaml#/presigned"

  # ─── INDEXER ───

  /indices/reindex:
    $ref: "./paths/indexer.yaml#/reindex"