openapi: 3.0.3
info:
  title: Vendo API
  version: 1.0.0
  description: Vendo Marketplace API

servers:
  - url: http://194.163.130.14:8030
    description: Vendo server

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      $ref: "./components/security.yaml"
  schemas:
    # ─── AUTH ────

    AuthRequest:
      $ref: "./schemas/auth/AuthRequest.yaml"
    AuthResponse:
      $ref: "./schemas/auth/AuthResponse.yaml"
    CompleteRequest:
      $ref: "./schemas/auth/CompleteRequest.yaml"
    GoogleAuthRequest:
      $ref: "./schemas/auth/GoogleAuthRequest.yaml"
    ProviderType:
      $ref: "./schemas/auth/ProviderType.yaml"
    RefreshRequest:
      $ref: "./schemas/auth/RefreshRequest.yaml"
    ResetPasswordRequest:
      $ref: "./schemas/auth/ResetPasswordRequest.yaml"
    UserResponse:
      $ref: "./schemas/auth/UserResponse.yaml"
    UserRole:
      $ref: "./schemas/auth/UserRole.yaml"

    # ─── EXCEPTION ─────

    ExceptionResponse:
      $ref: "./schemas/exception/ExceptionResponse.yaml"

    # ─── PRODUCT ─────

    Attribute:
      $ref: "./schemas/product/Attribute.yaml"
    AttributeType:
      $ref: "./schemas/product/AttributeType.yaml"
    AttributeValue:
      $ref: "./schemas/product/AttributeValue.yaml"
    CreateAttributeRequest:
      $ref: "./schemas/product/CreateAttributeRequest.yaml"
    CategoryResponse:
      $ref: "./schemas/product/CategoryResponse.yaml"
    CategoryTree:
      $ref: "./schemas/product/CategoryTree.yaml"
    CategoryTreeResponse:
      $ref: "./schemas/product/CategoryTreeResponse.yaml"
    CategoryType:
      $ref: "./schemas/product/CategoryType.yaml"
    CreateCategoryRequest:
      $ref: "./schemas/product/CreateCategoryRequest.yaml"
    ProductRequest:
      $ref: "./schemas/product/ProductRequest.yaml"
    ProductResponse:
      $ref: "./schemas/product/ProductResponse.yaml"
    FavoriteResponse:
      $ref: "./schemas/product/FavoriteResponse.yaml"
    FavoritesResponse:
      $ref: "./schemas/product/FavoritesResponse.yaml"

    # ─── SEARCH ─────

    SearchRequest:
      $ref: "./schemas/search/SearchRequest.yaml"

    # ─── STORAGE ─────

    PresignedRequest:
      $ref: "./schemas/storage/PresignedRequest.yaml"

paths:

  # ─── AUTH ────

  /auth/sign-up:
    $ref: "./paths/auth.yaml#/auth-signUp"

  /auth/sign-in:
    $ref: "./paths/auth.yaml#/auth-signIn"

  /auth/refresh:
    $ref: "./paths/auth.yaml#/auth-refresh"

  /auth/google:
    $ref: "./paths/auth.yaml#/auth-google"

  /auth/complete:
    $ref: "./paths/auth.yaml#/auth-complete"

  /auth/me:
    $ref: "./paths/auth.yaml#/auth-me"

  /password/forgot:
    $ref: "./paths/auth.yaml#/password"

  /password/reset:
    $ref: "./paths/auth.yaml#/password-reset"

  /password/resend-otp:
    $ref: "./paths/auth.yaml#/password-resend-otp"

  /verification/send-otp:
    $ref: "./paths/auth.yaml#/verification-send-otp"

  /verification/validate:
    $ref: "./paths/auth.yaml#/verification-validate"

  /verification/resend-otp:
    $ref: "./paths/auth.yaml#/verification-resent-otp"

  # ─── SEARCH ───

  /search:
    $ref: "./paths/search.yaml#/search"

  # ─── PRODUCTS ───

  /categories:
    $ref: "./paths/product.yaml#/categories"

  /categories/tree:
    $ref: "./paths/product.yaml#/categories-tree"

  /categories/{id}:
    $ref: "./paths/product.yaml#/category"

  /products:
    $ref: "./paths/product.yaml#/products"

  /products/{id}:
    $ref: "./paths/product.yaml#/product"

  /attributes:
    $ref: "./paths/product.yaml#/attributes"

  /favorites/{productId}:
    $ref: "./paths/product.yaml#/favorite"

  /favorites:
    $ref: "./paths/product.yaml#/favorites"

  # ─── STORAGE ───

  /storage/presigned:
    $ref: "./paths/storage.yaml#/presigned"

  # ─── INDEXER ───

  /indices/reindex:
    $ref: "./paths/indexer.yaml#/reindex"