type: object
properties:
  id:
    type: string
  title:
    type: string
  description:
    type: string
  quantity:
    type: number
  price:
    type: number
    format: double
  ownerId:
    type: string
  categoryId:
    type: string
  attributes:
    type: array
    items:
      $ref: "./AttributeValue.yaml"
  active:
    type: boolean
  createdAt:
    type: string
    format: date-time