type: object
properties:
  id:
    type: string
  title:
    type: string
  description:
    type: string
  quantity:
    type: number
  isNew:
    type: boolean
    example: true
  price:
    type: number
    format: double
  imageKeys:
    type: array
    items:
      type: string
  ownerId:
    type: string
  categoryId:
    type: string
  attributes:
    type: array
    items:
      $ref: "./AttributeValue.yaml"
  active:
    type: boolean
  createdAt:
    type: string
    format: date-time